### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by mauimauer** [maiera/gde-app#16]
An Android App that allows manual entry and tracking of content by sharing it with the App.
Ideally this would be hooked up to the backend of the existing GDE Web Tracking App.

Please let me and the other Android GDEs know if you want us to do it. We'd love to help

**Comment by SmokyBob** [comment]
Closing because the Web FrontEnd moved to the [Google Developer Experts Org](https://github.com/GoogleDeveloperExperts) and there are no news since November.
The new FE is based on [Polymer Starter Kit](https://developers.google.com/web/tools/polymer-starter-kit/) and we plan to make use of all the features provided like service worker to enable the app to work offline and App Install.
Feel free to create a repo on the Google Developer Experts Org if an android app is being developed
