### ISSUE TITLE
Move repository to GoogleDeveloperExperts org

### ISSUE THREAD

**Issue by zenorocha** [maiera/gde-app#164]
Hey @maiera,

We created an org to host projects related to the GDE program: https://github.com/GoogleDeveloperExperts

I think it would be a good idea to move this repository to that org as well (your invitation has been already sent).

**Comment by Scarygami** [comment]
The frontend will be further developed (mostly from scratch) at https://github.com/GoogleDeveloperExperts/gde-app-web

The backend will be moved to https://github.com/GoogleDeveloperExperts/gde-app-backend

Having them in separate repos makes maintenance much easier as well, than having them in the same repo in different branches.

@SmokyBob do we want to copy the current frontend source to a branch on gde-app-web to keep it around for historic reasons and fixes that might be necessary while the new frontend is in development?

Because then we could completely retire this repository. We still have to go through the issues and copy the ones that are still relevant to the new repo(s).

**Comment by SmokyBob** [comment]
I think it's a good idea having a branch with the current version, but instead of from this repo we could use the one from connected to the Jenkins deploy job (same code but structured to be server by GAE).

**Comment by Scarygami** [comment]
@SmokyBob sure, feel free to add any code that you feel will make maintenance easiest for you. We can probably adjust the Jenkins deploy job to read from this branch then as well.

@patt0 I've moved the current backend source to https://github.com/GoogleDeveloperExperts/gde-app-backend. Can you check if everything is in order there and use this as our main repo from now on?

**Comment by patt0** [comment]
Yes I am happy to report that it looks as if its all ok !!!

**Comment by SmokyBob** [comment]
Created HTML5 branch with the current prod source structured to be served by GAE.
Updated the prod Jenkins build to use the new repo and branch.

Time to copy the issues \o/

**Comment by Scarygami** [comment]
Well, I guess that's done then, thanks for copying all the issues :) I'll leave the honour to close this issue to you ;)

**Comment by SmokyBob** [comment]
Eheh
sorry for the git mail spam
