### ISSUE TITLE
Can't add any new activities.

### ISSUE THREAD

**Issue by umaar** [maiera/gde-app#196]
I'm getting `Only GDEs and admins may enter or change data.` My ID is: 111696301786817020074

In the console, I do see: `You are a GDE` so not sure what the problem is.

**Comment by patt0** [comment]
Which url are you hitting to access the application? We have been having
problems with gweb.io these past few weeks.

We are testing app engine based hosting, please do try the following and
let me know how that is going?

https://gdetracking.appspot.com/

Best


Patrick Martinent

**Comment by SmokyBob** [comment]
@umaar Checked the log and the problem seems to be that the email associated to your account in the GDE Tracking App does not match the one linked to the Google Account.

Changed the email in the datastore to the one associated to the Google + account, please try again and let us know if there is any problem.

**Comment by umaar** [comment]
Thank you @SmokyBob ! Appreciate the quick fix, I can log new activities now.
